name: Deploy Laravel to Azure

on:
  push:
    branches:
      - main  # Pastikan branch lu 'main' atau 'master'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Dependencies
        run: |
          cd WebVersion
          composer install --prefer-dist --optimize-autoloader --no-dev

      - name: Zip artifact for deployment
        run: |
          cd WebVersion
          zip -r release.zip . -x "node_modules/*" ".git/*" "storage/*.log"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'laravel-app-1763830183' 
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./WebVersion/release.zip
